"""
Douyin product parser using Playwright
"""
import os
import time
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

# Try to import playwright
try:
    from playwright.sync_api import sync_playwright
    PLAYWRIGHT_AVAILABLE = True
except ImportError:
    PLAYWRIGHT_AVAILABLE = False

# Try to import BeautifulSoup
try:
    from bs4 import BeautifulSoup
    BS4_AVAILABLE = True
except ImportError:
    BS4_AVAILABLE = False


STORAGE_FILE = "storage.json"
TIMEOUT = 15000  # 15 seconds


def parse_douyin_product(url: str) -> Dict[str, Any]:
    """
    Parse Douyin product using Playwright

    Args:
        url: Douyin product URL

    Returns:
        Dict with name, selling_points, comments
    """
    if not PLAYWRIGHT_AVAILABLE:
        logger.warning("Playwright not installed")
        return {
            "name": "",
            "selling_points": "",
            "comments": []
        }

    print("正在使用 Playwright 抓取抖音商品...")

    try:
        with sync_playwright() as p:
            # Check if storage file exists
            storage_state = None
            if os.path.exists(STORAGE_FILE):
                storage_state = STORAGE_FILE
                print(f"使用已保存的登录状态: {STORAGE_FILE}")

            # Launch browser (visible, not headless)
            browser = p.chromium.launch(
                headless=False,
                args=['--disable-blink-features=AutomationControlled']
            )

            context = browser.new_context(
                storage_state=storage_state,
                viewport={'width': 1280, 'height': 720}
            )

            page = context.new_page()

            # If no storage, wait for user to login
            if not storage_state:
                print("请在弹出的浏览器中扫码登录抖音...")
                print("等待30秒...")
                time.sleep(30)

                # Save storage state
                context.storage_state(path=STORAGE_FILE)
                print(f"登录状态已保存到: {STORAGE_FILE}")

            # Navigate to product URL
            print(f"正在打开商品链接: {url}")
            page.goto(url, timeout=TIMEOUT, wait_until="domcontentloaded")

            # Wait for page to load
            page.wait_for_timeout(5000)

            # Get HTML content
            html = page.content()
            print(f"HTML长度: {len(html)}")

            # Extract data using BeautifulSoup
            result = _extract_from_html(html)

            browser.close()

            return result

    except Exception as e:
        logger.error(f"Playwright parsing failed: {e}")
        print(f"解析失败: {e}")
        return {
            "name": "",
            "selling_points": "",
            "comments": []
        }


def _extract_from_html(html: str) -> Dict[str, Any]:
    """Extract product info from HTML"""
    if not BS4_AVAILABLE:
        return {
            "name": "",
            "selling_points": "",
            "comments": []
        }

    try:
        soup = BeautifulSoup(html, 'html.parser')

        # Extract title
        name = ""

        # Try og:title
        og_title = soup.find("meta", property="og:title")
        if og_title and og_title.get("content"):
            name = og_title["content"].strip()

        # Try title tag
        if not name:
            title = soup.find("title")
            if title:
                name = title.get_text().strip()
                name = name.split('|')[0].split('-')[0].strip()

        # Try h1
        if not name:
            h1 = soup.find("h1")
            if h1:
                name = h1.get_text().strip()

        # Extract selling points from page text
        selling_points = ""
        body = soup.find("body")
        if body:
            text = body.get_text()
            # Clean and get first 200 chars
            text = ' '.join(text.split())
            selling_points = text[:200]

        return {
            "name": name,
            "selling_points": selling_points,
            "comments": []  # Comments will be generated by AI
        }

    except Exception as e:
        logger.error(f"HTML extraction failed: {e}")
        return {
            "name": "",
            "selling_points": "",
            "comments": []
        }
