"""
Simple product URL parser
Uses requests + regex for basic HTML parsing (no external dependencies)
"""
import re
import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

try:
    import requests
except ImportError:
    requests = None


def parse_product(url: str) -> Dict[str, Any]:
    """
    Parse product information from URL using simple HTML parsing

    Args:
        url: Product URL

    Returns:
        Dict with name, selling_points, comments, product_info
    """
    if not requests:
        logger.warning("requests not installed, using empty result")
        return {
            "name": "",
            "selling_points": "",
            "comments": [],
            "product_info": ""
        }

    try:
        # Use session to handle cookies
        session = requests.Session()
        session.trust_env = False  # Disable system proxy
        session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
            "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
        })

        response = session.get(url, timeout=10)
        response.raise_for_status()

        html = response.text

        # Extract product name from title
        name = _extract_name(html)

        # Extract selling points
        selling_points = _extract_selling_points(html)

        # Extract product info
        product_info = _extract_product_info(html)

        logger.info(f"Parsed product: {name}, selling_points: {selling_points[:50] if selling_points else ''}...")

        return {
            "name": name,
            "selling_points": selling_points,
            "comments": [],  # Comments will be generated by AI
            "product_info": product_info
        }

    except Exception as e:
        logger.error(f"Failed to parse URL {url}: {e}")
        return {
            "name": "",
            "selling_points": "",
            "comments": [],
            "product_info": ""
        }


def _extract_name(html: str) -> str:
    """Extract product name from page"""
    # Try og:title
    match = re.search(r'<meta[^>]+property=["\']og:title["\'][^>]+content=["\']([^"\']+)["\']', html, re.I)
    if match:
        return match.group(1).strip()

    # Try og:title reversed
    match = re.search(r'<meta[^>]+content=["\']([^"\']+)["\'][^>]+property=["\']og:title["\']', html, re.I)
    if match:
        return match.group(1).strip()

    # Try title tag
    match = re.search(r'<title[^>]*>([^<]+)</title>', html, re.I)
    if match:
        title_text = match.group(1).strip()
        # Clean title (remove site name after | or -)
        title_text = re.sub(r'[|_‑\-].*$', '', title_text)
        return title_text.strip()

    # Try h1
    match = re.search(r'<h1[^>]*>([^<]+)</h1>', html, re.I)
    if match:
        return match.group(1).strip()

    return ""


def _extract_selling_points(html: str) -> str:
    """Extract selling points from page"""
    # Try meta description
    match = re.search(r'<meta[^>]+name=["\']description["\'][^>]+content=["\']([^"\']+)["\']', html, re.I)
    if match:
        return match.group(1).strip()

    # Try meta description reversed
    match = re.search(r'<meta[^>]+content=["\']([^"\']+)["\'][^>]+name=["\']description["\']', html, re.I)
    if match:
        return match.group(1).strip()

    # Try og:description
    match = re.search(r'<meta[^>]+property=["\']og:description["\'][^>]+content=["\']([^"\']+)["\']', html, re.I)
    if match:
        return match.group(1).strip()

    # Try og:description reversed
    match = re.search(r'<meta[^>]+content=["\']([^"\']+)["\'][^>]+property=["\']og:description["\']', html, re.I)
    if match:
        return match.group(1).strip()

    # Try to find price section
    match = re.search(r'<[^>]+class=["\'][^"\']*price[^"\']*["\'][^>]*>([^<]+)</', html, re.I)
    if match:
        return match.group(1).strip()[:200]

    # Try keywords meta
    match = re.search(r'<meta[^>]+name=["\']keywords["\'][^>]+content=["\']([^"\']+)["\']', html, re.I)
    if match:
        return match.group(1).strip()

    return ""


def _extract_product_info(html: str) -> str:
    """Extract product basic info (material, features, etc.)"""
    # Look for specs or parameters section
    match = re.search(r'<[^>]+class=["\'][^"\']*(?:spec|parameter|detail)[^"\']*["\'][^>]*>([\s\S]*?)</', html, re.I)
    if match:
        text = match.group(1)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()[:300]

    return ""


def detect_platform(url: str) -> str:
    """Detect e-commerce platform from URL"""
    url_lower = url.lower()

    if "taobao" in url_lower or "tb" in url_lower:
        return "taobao"
    elif "tmall" in url_lower:
        return "tmall"
    elif "douyin" in url_lower or "抖音" in url:
        return "douyin"
    elif "jd" in url_lower or "jingdong" in url_lower or "京东" in url:
        return "jd"
    elif "pinduoduo" in url_lower or "拼多多" in url:
        return "pinduoduo"
    else:
        return "unknown"
